### ISSUE TITLE
Still redirecting to /admin while logged into the CMS

### ISSUE THREAD

**Issue by bdougie** [netlify-templates/one-click-hugo-cms#1]
I am noticing that while I am logged into the CMS, I cannot view the homepage and get redirected back to "/admin". I see this commit [ab57ad3b7547089eee9a2fb4484c370ef6730c2a](https://github.com/netlify-templates/one-click-hugo-cms/commit/ab57ad3b7547089eee9a2fb4484c370ef6730c2a) should solve this issue, but that is not the case on the site I just cloned from this template: https://cook-doris-42316.netlify.com

I have to log out to view the homepage

**Comment by wiesson** [comment]
I also noticed this issue. Why is there a redirect to admin in the first place? If I would like to access the admin area, then I go manually to /admin (?)

**Comment by bdougie** [comment]
Right there with you @wiesson. I am going to open a PR #3 removing it. @biilmann let us know if there was another reason for this code that is not apparent.

**Comment by erquhart** [comment]
I believe this has since been addressed between updates to [this repo](https://github.com/netlify-templates/one-click-hugo-cms/commit/5cc56682c49c017e391d42f7e8a6b81e890ddb4c) and to the widget library. Closing.
