### ISSUE TITLE
Where do we edit the CSS?

### ISSUE THREAD

**Issue by swallowingspecialist** [netlify-templates/one-click-hugo-cms#103]
The admin page is really helpful but have not been successful finding the CSS responsible for the layout. 

The left panel shows the paragraphs nicely divided but when it appears on the actual site, it becomes a big lump of words. 

Thanks.

![broken_css](https://user-images.githubusercontent.com/31624421/50545074-e40e5f00-0c43-11e9-8825-540cb3abca3e.png)

**Comment by erquhart** [comment]
You'll want to use the markdown widget for formatted text. The text widget you're using provides a multiline interface, but newlines and other formatting aren't going to work there.

**Comment by iColdPlayer** [comment]
@erquhart Hi, Thank for sharing this awesome theme. Currently, I'm using this theme for my portfolio.
But somehow I need to change the size of the single poss / single page.
Cause by the default it looks bit small, can you provide me about how to change the _"width"_ of the single post is?

**Comment by erquhart** [comment]
There are a few custom styles here: https://github.com/netlify-templates/gatsby-starter-netlify-cms/blob/master/src/components/all.sass

The blog post template itself is here: https://github.com/netlify-templates/gatsby-starter-netlify-cms/blob/master/src/templates/blog-post.js

The template component uses classes from the Bulma framework: https://bulma.io/

Hope it helps!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
