### ISSUE TITLE
No media loading and uploading for Deploy to Netlify

### ISSUE THREAD

**Issue by michalskop** [netlify-templates/one-click-hugo-cms#116]
I found the problem with no pictures shown in Media and unable to upload them, too.

I have used the `Deploy to Netlify` button to try it.

It is the same issue as closed https://github.com/netlify/netlify-cms/issues/1565 or closed https://github.com/netlify/netlify-cms/issues/1608, so it seems to me that it is solved generally, but not for the one-click example?

**Comment by erquhart** [comment]
Netlify CMS just hasn't been updated in the starter, try upgrading to 2.8.0.
