### ISSUE TITLE
CMS update issue

### ISSUE THREAD

**Issue by SherG** [netlify-templates/one-click-hugo-cms#119]
Seems that since the NetlifyCMS update, deploying a new instance of one-click-hugo-cms results in the right-hand pane of the CMS not having its usual WYSIWIG features.

Below: Normal right-hand pane view + current right-hand pane view with newly launched one-click-hugo-cms sites. 

(Note: This also happens w/the [NetlifyCMS-Gatsby site](https://www.netlifycms.org/docs/start-with-a-template/), with a slight difference: _**after** initial deploy_, once you update to NetCMS2.8.0, the right-pane loses its WYSIWIG display features.)
![normal-view](https://user-images.githubusercontent.com/10387946/55125206-5c6bab80-50df-11e9-9083-e657bf3b8eb9.png)
![new-initial-deployment](https://user-images.githubusercontent.com/10387946/55125207-5d044200-50df-11e9-81da-bbb668b652a4.png)

**Comment by erquhart** [comment]
Netlify CMS has been updated to address this, you'll want to get 2.9.0 or greater.
