### ISSUE TITLE
Applying markdown to Pages

### ISSUE THREAD

**Issue by SherG** [netlify-templates/one-click-hugo-cms#124]
Re: 
https://github.com/netlify-templates/one-click-hugo-cms/issues/103#issuecomment-455379515

I've tried to apply the markdown widget to pages so hyperlinks and paragraph formatting can be added to Pages. The markdown editing pane now appears in the CMS. But adding hyperlinks to text causes actual markdown to appear in the live page, and no hyperlinks appear. (Same with line breaks, paragraph tags.)

Is this use of `widget:"markdown"` incorrect? (config.yml) Thanks!

           - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "markdown"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "markdown"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "markdown"}]}

**Comment by erquhart** [comment]
Hugo will automatically process a markdown file's body as markdown, but you're putting markdown into frontmatter fields (or a data file, can't tell from your snippet). You'll need to use the `markdownify` template function explicitly to get Hugo to parse a specific value as Markdown.

Reference: https://discourse.gohugo.io/t/markdown-in-front-matter/1004
