### ISSUE TITLE
Netlify Identity widget is loaded on every page (160kb)

### ISSUE THREAD

**Issue by marcojakob** [netlify-templates/one-click-hugo-cms#127]
Is it really necessary to load the Netlify Identity widget on every page? Currently, it's a blocking 160kb in the head section.

`<script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>`

See https://github.com/netlify-templates/one-click-hugo-cms/blob/master/site/layouts/partials/head.html#L26

I don't quite understand:

- Where do we really need it? Would the `/admin/` page be sufficient?
- Could we do an async load instead?

**Comment by SherG** [comment]
Re: head placement, Tomango has theirs below footer: view-source:https://www.tomango.co.uk/ 

https://github.com/tomangoUK/tomango-2018/search?q=netlifyIdentity&unscoped_q=netlifyIdentity

**Comment by marcojakob** [comment]
> Re: head placement, Tomango has theirs below footer: view-source:https://www.tomango.co.uk/
> 
> https://github.com/tomangoUK/tomango-2018/search?q=netlifyIdentity&unscoped_q=netlifyIdentity

@SherG I only see the identity widget in https://www.tomango.co.uk/admin/

The code in the footer with `window.netlifyIdentity` will not do anything unless the identity widget is included.

**Comment by erquhart** [comment]
The identity widget has to be present on a site's home page as authentication works with a site's root. I don't believe it needs to be on other pages.
