### ISSUE TITLE
Editing the Template Title

### ISSUE THREAD

**Issue by mryap** [netlify-templates/one-click-hugo-cms#18]
hi, 

When I post a link of my website (based on one-click-hugo-cms) on Twitter, it still shows Kaldi | Coffee with a Conscience. 

How do I remove it? 

![kaldi-screenshots](https://user-images.githubusercontent.com/15719191/37209693-04e89ce8-239e-11e8-8f79-ca78422c0fdb.png)

Thank You

**Comment by erquhart** [comment]
Right here: https://github.com/netlify-templates/one-click-hugo-cms/blob/5cc1f9b3670f06431775e026e5f9ea334e5a1e47/site/layouts/partials/head.html#L22
