### ISSUE TITLE
Document custom fork of styling?

### ISSUE THREAD

**Issue by easherma** [netlify-templates/one-click-hugo-cms#21]
Hi all, 

Been enjoying using this template as a starting point. Could there be an explanation of why the choice was made to go with a custom fork of Tachyons and/or PostCSS, what the differences are, and how to best account for that if we want to update Tachyons or use other tooling on the css side of things?

**Comment by easherma** [comment]
@erquhart I understand that, but it would be easier to adopt with some documentation on the differences of this custom version, especially if someone is unfamiliar with PostCSS or new to Tachyons. 

For instance, I just spent awhile debugging some odd behavior on my site and have deduced that _states.css is probably a custom add. Is this correct? If so, a list of these and others in the readmes and/or in the css files themselves would help. Happy to coordinate on a PR!

**Comment by erquhart** [comment]
Agreed, that's why I don't use Tachyons lol. If any effort went toward the problem you're describing, I think it should be toward getting this project off of Tachyons.

Otherwise, if you prefer to contribute documentation, that's great too.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by easherma** [comment]
@darindimitroff you are the original creator, right? Any thoughts on this?

**Comment by darindimitroff** [comment]
I can add some documentation around the custom fork, but I don’t plan on implementing vanilla Tachyons. Most people using the template might not be familiar with Tachyons to begin with, so the idea is to use the atomic patterns as a useful paradigm in general.

**Comment by easherma** [comment]
@darindimitroff I'm not following the logic there, but I understand you not wanting to do the work to revert to a vanilla Tachyons. 

Most people may unfamiliar with Tachyons, but everyone besides yourself is unfamiliar with whatever extensions or modifications you made. It seems like if that was a concern we'd have more explicit documentation of the styling here and/or how it varies from vanilla Tachyons, or we'd call it a day and use vanilla Tachyons and point to their docs.

That being said, I greatly appreciate this template as I've been able to build off it and learn how to use Netlify at the same time and have actually learned Tachyons through this template. That being said, in my fork I've also pretty much slowly replaced much of the css with vanilla Tachyons. :-D

**Comment by erquhart** [comment]
We'll definitely contributions towards improvement! Closing for now but do comment if there's anything further.
