### ISSUE TITLE
Does not run with `netlify dev` command

### ISSUE THREAD

**Issue by clintonc** [netlify-templates/one-click-hugo-cms#424]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
After running `npm install`, the command `npm start` works, but `netlify dev` does not, once it's set up.

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a new project (mine is based at commit `9d20f73dfbaea4531ab4b3e36fb9c9a56687743a`).
2. Run `npm install` to install dependencies.
3. Authenticate and link the netlify CLI to the project.
4. Run `netlify dev` and see the following error:
    ```
    ◈ Netlify Dev ◈
    ◈ Starting Netlify Dev with hugo
    Error: "hugo" could not be found in your PATH. Please make sure that "hugo" is installed and available in your PATH
    ```
5. Run `PATH=$PATH:node_modules/hugo-bin/vendor netlify dev` and see the message
    ```
    WARN 2020/05/02 21:58:59 found no layout file for "HTML" for kind "hom
    ```

**- What is the expected behavior?**
`netlify dev` should serve the generated site.
**- Please mention your node.js, NPM, Hugo and operating system version.**

node v13.2.0 (and 14.1.0)
npm 6.14.4
hugo -- none installed on the system
MacOS 10.15.4 (19E287)

**Comment by maxcell** [comment]
There have been updates to the project so this should work now with the latest `main` branch! Thank you for the report on this! I am not certain what may have happened to cause the issue then.
