### ISSUE TITLE
can this framework be used locally to generate /public folder to be deployed elsewhere?

### ISSUE THREAD

**Issue by abioneperhobby** [netlify-templates/one-click-hugo-cms#63]
i want to use this cms locally to generate the /public folder that will be deployed in my website custom domain.

i'm not able to understand how to do this.

i can locally run the cms connecting to netlify account; but instead i want to run locally the cms only to easily manage content generation.

is this possible?

thanks.

**Comment by erquhart** [comment]
Netlify CMS will make changes in your hosted repository (e.g. on GitHub, GitLab, etc). You can run Netlify CMS locally and it will still only edit your hosted repository and not your local Git repo. If you want to build locally, you'll need to pull down the changes that Netlify CMS makes in your hosted repository.

**Comment by abioneperhobby** [comment]
Understand. 
Thanks
