### ISSUE TITLE
Image preview on Value page not working

### ISSUE THREAD

**Issue by JudiPuak** [netlify-templates/one-click-hugo-cms#647]
I have deployed this repo to netlify without any problem.  Admin works too.

But I have noticed something weird
Steps to reproduce:
Go to admin and click Value page to edit the page.  (All the images are there in the preview)
Change the image of the first value and now the image of this first value is gone from the preview pane although it's still there in the edit pane.

I've run this locally and it's exactly like that too:  I changed the image of the first value and now that image is gone from the preview pane, the other images are still there.

I've played around with src/js/cms-preview-templates/value.js but I am totally lost here.

Any help would be greatly appreciated.  Thank you.

**Comment by JudiPuak** [comment]
Never mind.  I have found the workaround to solve this issue.

**Comment by merwok** [comment]
Do you mind sharing it?

**Comment by JudiPuak** [comment]
@merwok 

yes sure
open ````src/js/cms-preview-templates/values.js````

locate this snippet of code in or near line 37:

```
<div className="bg-off-white pv4">
        <div className="mw7 center ph3 pt4">
          {values.map(({text, heading, imageUrl}, i) =>
            <MediaBlock key={i} text={text} heading={heading} imageUrl={imageUrl} reverse={i % 2 === 0} />
          )}
        </div>
      </div>
````
change it into:
````
<div className="bg-off-white pv4">
        <div className="mw7 center ph3 pt4">
          {values.map(({text, heading, imageUrl}, i) =>            
            <div className="ph2-ns w-100-ns mb4" key={i}>
              <img src={imageUrl && getAsset(imageUrl)} alt="" className="center db mb3" style={{width: "480px"}}/>
              <h3 className="f2 b lh-title mb2">{heading}</h3>
              <p>{text}</p>
            </div>)}          
        </div>
      </div>
````

So basically, we don't use the MediaBlock anymore.  You can now delete the MediaBlock const (line 6 - 19) or you can just leave it there.

Please let me know if it works for you too.
