### ISSUE TITLE
Bug: 1-click site generation fails

### ISSUE THREAD

**Issue by nagyv** [netlify-templates/one-click-hugo-cms#651]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

The 1-click site generation does not work

<img width="782" alt="Képernyőfotó 2021-11-21 - 20 36 15" src="https://user-images.githubusercontent.com/126671/142776452-646fa196-1bf8-42ed-9f75-6fbd89b69358.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**

- Click the "Deploy to Netlify button"
- Connect with GitHub
- Provide name for repo
- Hit continue button

**- What is the expected behavior?**

- The new repo is populated as advertised with everything set up

**- Please mention your node.js, NPM, Hugo and operating system version.**

-

**Comment by maxcell** [comment]
Howdy @nagyv! This is a strange bug!! If you wouldn't mind trying the workflow again? I just clicked the button in [our README](https://github.com/netlify-templates/one-click-hugo-cms#getting-started) and didn't experience this error so I couldn't reproduce it. If you have space and time, a recording/GIF would be helpful too!

**Comment by maxcell** [comment]
Ended up doing a huge set of dependency updates so let me know if this is all working for you for deployments! I couldn't reproduce it myself again but hoping this reduce any issues for the future!
