### ISSUE TITLE
Trying to change the orange colour

### ISSUE THREAD

**Issue by bwhybrow23** [netlify-templates/one-click-hugo-cms#97]
Hello I am trying to change the orange color on the template on my website for #71c4f7 (light blue). I have changed it in the _variables.css and it isn't working. Any help? 

Website: https://www.kewls.net/
Github Repo: https://github.com/bwhybrow23/kewl-website

**Comment by erquhart** [comment]
Looks light blue to me :)

**Comment by bwhybrow23** [comment]
Yeah, I had to CTRL+F5. Sorry about that.

**Comment by erquhart** [comment]
No problem, glad you got it figured!
